name: Contracts

on:
  push:
    paths:
      - 'contracts/**'
      - '.github/workflows/contracts.yml'
  pull_request:
    paths:
      - 'contracts/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        working-directory: contracts
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
      - name: Compile (clean and force)
        working-directory: contracts
        run: |
          npx hardhat clean
          npx hardhat compile --force
      - name: Test
        working-directory: contracts
        run: |
          npx hardhat test
      - name: Deploy to in-process hardhat network
        working-directory: contracts
        run: |
          npx hardhat run scripts/deploy.js
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: contract-artifacts
          path: |
            contracts/artifacts
            contracts/deployments
            contracts/deployed_addresses.json
