name: Python tests

on:
  push:
    branches: [ main, master ]
    paths-ignore:
      - 'badges/**'
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov coverage-badge

      - name: Run targeted tests with coverage and timings
        run: |
          pytest -q tests/test_redact_tx_minimal.py --cov=. --cov-report=term-missing --durations=10

      - name: Run broader subset (no performance) with coverage and timings
        if: matrix.python-version == '3.10'
        run: |
          pytest -q tests -k "not performance" --cov=. --cov-report=term-missing --durations=10

      - name: Generate coverage badge
        if: matrix.python-version == '3.10'
        run: |
          coverage-badge -o coverage.svg -f || true

      - name: Commit coverage badge to repo
        if: matrix.python-version == '3.10' && github.event_name == 'push'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p badges
          mv coverage.svg badges/coverage.svg || true
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add badges/coverage.svg
          git diff --staged --quiet || git commit -m "Update coverage badge [skip ci]"
          git push

      - name: Upload coverage artifacts
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-reports
          path: |
            coverage.svg
            .coverage
