name: Python tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest pytest-cov coverage-badge

      - name: Run targeted tests with coverage and timings
        run: |
          pytest -q tests/test_redact_tx_minimal.py --cov=. --cov-report=term-missing --durations=10

      - name: Run broader subset (no performance) with coverage and timings
        if: matrix.python-version == '3.10'
        run: |
          pytest -q tests -k "not performance" --cov=. --cov-report=term-missing --durations=10

      - name: Generate coverage badge
        if: matrix.python-version == '3.10'
        run: |
          coverage-badge -o coverage.svg -f || true

      - name: Upload coverage artifacts
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-and-reports
          path: |
            coverage.svg
            .coverage
